apiVersion: apps/v1
kind: Deployment

metadata:
    name: PHP-Frontend

spec:
    replicas: 1

    selector:
        matchLabels:
            app: PHP-Frontend

    template:
        metadata:
            labels:
                app: PHP-Frontend

        spec:
            containers:
            - name: Frontend
                image: front-end-image
                ports:
                - containerPort: 80
                    imagePullPolicy: IfNotPresent

---

apiVersion: v1
kind: Service

metadata:
    name: PHP-Frontend
    labels:
        app: PHP-Frontemd

spec:
    selector:
        app: PHP-Frontend

    ports:
    - port: 80
        protocol: TCP
        targetPort: 80

    type: NodePort
