name: web-app

pod:
    name: website-container
    image: website-image

    containerPort: 80
    imagePullPolicy: IfNotPresent

service:
    selector: web-app
    type: NodePort
    port: 80
    targetPort: 80
